export const CONFIG = {};

export const SELECTED_ITEMS = {
	ACTIVATE_MULTISELECT: 'ACTIVATE_MULTISELECT',
	DEACTIVATE_MULTISELECT: 'DEACTIVATE_MULTISELECT',
	TOGGLE_SELECTED: 'TOGGLE_SELECTED',
	GROUP_SELECT: 'GROUP_SELECT',
	CLEAR_SELECTION: 'CLEAR_SELECTION'
};
